sudo: required

before_install:
  - sudo apt-get install qtdeclarative5-dev

# Enable C++ support
language: cpp

# Compiler selection
compiler:
- gcc

script:
  - mkdir build
  - cd build
  - cmake ../
  - make
