sudo: required

before_install:
  - sudo add-apt-repository --yes ppa:levi-armstrong/qt-libraries-trusty
  - sudo apt-get update -qq
  - sudo apt-get install qt57declarative 

# Enable C++ support
language: cpp

# Compiler selection
compiler:
- gcc

script:
  - mkdir build
  - cd build
  - cmake ../
  - make
